import os

from dotenv import load_dotenv


load_dotenv()


SLACK_APP_ID = 'A08CQENU45N'
SLACK_CLIENT_ID = '8372551828167.8432498956192'

SLACK_CLIENT_SECRET = os.getenv('SLACK_CLIENT_SECRET')
SLACK_SIGNING_SECRET = os.getenv('SLACK_SIGNING_SECRET')
SLACK_VERIFICATION_TOKEN = os.getenv('SLACK_VERIFICATION_TOKEN')

SLACK_APP_TOKEN_NAME = 'my-app-token'
SLACK_APP_TOKEN = os.getenv('SLACK_APP_TOKEN')

SLACK_BOT_TOKEN = os.getenv('SLACK_BOT_TOKEN')
